# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHubAPIExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHubAPIExample


  # Rx
  pod 'Moya/RxSwift', '~> 14.0.0' 
  pod 'Moya-ObjectMapper/RxSwift', '~> 2.0'  
  pod 'RxCocoa', '~> 5'
  pod "RxGesture", '~> 3.0.1'

  # Codes
  pod 'SnapKit', '~> 5.0' # Auto Layout
  pod 'Then'

  # Data
  pod 'SwiftyJSON', '~> 5.0.0'

  # UI
  pod 'Kingfisher', '~> 5.0' # Image Processor


  target 'GitHubAPIExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitHubAPIExampleUITests' do
    # Pods for testing
  end

end
